apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
  labels:
    name: django-migrate
    type: migrate
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: galbirk/django-k8s-monitor:latest
        command: ["bash","-c","/app/migrate.sh"]
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
        ports:
          - containerPort: 8000
            name: gunicorn
      restartPolicy: OnFailure
  backoffLimit: 4
