language: python

services:
  - docker

before_install:
 - cd app && docker build --no-cache -t ${DOCKER_HUB_USER}/${DOCKER_HUB_REPO} .
 - cd ../db && docker build --no-cache -t ${DOCKER_HUB_USER}/django-k8s-monitor-postgres .

script:
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  - docker push ${DOCKER_HUB_USER}/${DOCKER_HUB_REPO}
  - docker push ${DOCKER_HUB_USER}/django-k8s-monitor-postgres
  - docker-compose up -d
  - curl --insecure http://127.0.0.1:8000