apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: monitor-k8s
spec:
  #serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: monitor-k8s
  template:
    metadata:
      labels:
        app: monitor-k8s
    spec:
      containers:
      - name: postgres
        image: galbirk/django-k8s-monitor-postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv-volume
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: monitor-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor-k8s
  template:
    metadata:
      labels:
        app: monitor-k8s
    spec:
      containers:
        - image: galbirk/django-k8s-monitor:latest
          name: django
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: gunicorn
