apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
    replicas: 1
  selector:
    matchLabels:
      app: monitor-k8s
  template:
    metadata:
      labels:
        app: monitor-k8s
    spec:
      containers:
        - name: postgres
          image: galbirk/django-k8s-monitor-postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: monitor-k8s
spec:
    replicas: 2
  selector:
    matchLabels:
      app: monitor-k8s
  template:
    metadata:
      labels:
        app: monitor-k8s
    spec:
      containers:
        - image: galbirk/django-k8s-monitor:latest
          name: django
          envFrom:
          - secretRef:
              name: django-secrets
          - configMapRef:
              name: django-config
          ports:
            - containerPort: 8000
              name: gunicorn
