apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: monitor-k8s
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: monitor-k8s
  template:
    metadata:
      labels:
        app: monitor-k8s
    spec:
      containers:
      - name: postgres
        image: galbirk/django-k8s-monitor-postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv-volume
        persistentVolumeClaim:
          claimName: postgres-pv-claim